Feat/htd 33 feature line
bejamas/httptoolkit-website pull request #35
Opened 2024-03-01 00:22 UTC by RBoraurito

## Pull Request Description

## Assets

| before | after |
| ------ | ----- |
|        |       |

## Before Merge Checklist

The following steps were checked before merging a PR

- [ ] checked and fixed code style issues
- [ ] checked and removed unnecessary/junky code
- [ ] manually tested introduced solution
- [ ] added needed tests to automate testing this code in the future

2024-03-04 17:12 UTC, nephlin7 requested changes

2024-03-04 17:12 UTC, nephlin7 commented on public/images/mockup-image-light.jpg
Can we optimize the images? Let's convert these images to `.webp` format, please. Here you can find some useful tools for it:

1. compress file: https://tinypng.com/
2. convert to webp: https://cloudconvert.com/png-to-webp

> Note: Before converting it to `webp`, make sure to export the image in PNG from Figma to avoid the white background

2024-03-04 17:12 UTC, nephlin7 commented on src/components/modules/text-list/index.tsx
> +          <CheckIcon />{' '}
```suggestion
          <CheckIcon />
```

2024-03-04 17:12 UTC, nephlin7 commented on src/components/sections/feature-line/index.tsx
> +      <StyledFeatureLineImage darkSrc={darkImage} lightSrc={lightImage} alt={alt} withBorderAnimation />
The image should have a border but without the animation. Can you extend it to have `withBorder` prop?
```suggestion
      <StyledFeatureLineImage darkSrc={darkImage} lightSrc={lightImage} alt={alt} withBorder />
```

2024-03-04 17:12 UTC, nephlin7 commented on src/components/sections/feature-line/index.tsx
Could you add an example when all the [images are on the right](https://www.figma.com/file/O5411bxKHP2O2OyfW19w6E/HTTP-Toolkit---UI-Design?type=design&node-id=305-3123&mode=design&t=NRUspd3SjkWh87NV-0)? 

<img width="269" alt="Screenshot 2024-03-04 at 11 06 22" src="https://github.com/bejamas/httptoolkit-website/assets/22168189/d0f6bd92-7ee3-4950-b377-79119ea4eff3">

2024-03-04 17:12 UTC, nephlin7 commented on public/images/mockup-image.jpg
The same as the previous comment, Also could initially export the image as PNG from Figma to avoid the white border?

2024-03-04 17:18 UTC, RBoraurito commented on public/images/mockup-image-light.jpg
I got it; I was thinking of optimizing the images at the end to do it all at once.

2024-03-05 06:00 UTC, nephlin7 requested changes

2024-03-05 06:00 UTC, nephlin7 commented on public/images/mockup-image-light.jpg
Since we will use the same placeholders everywhere, I think it's better to do it now :D

2024-03-05 06:00 UTC, nephlin7 commented on src/components/elements/themed-image/themed-image.ts
> +  aspect-ratio: 1 / 1;
Can we remove the aspect ratio? This is breaking some images in other places:

![Screenshot 2024-03-04 at 15 59 44](https://github.com/bejamas/httptoolkit-website/assets/22168189/1328950c-cbed-4f9f-9eb7-be91427b3cd0)

2024-03-06 16:17 UTC, nephlin7 approved these changes
@RBoraurito, Just check the bottom spacing of each section before merging, please.
<img width="1291" alt="Screenshot 2024-03-06 at 10 16 29" src="https://github.com/bejamas/httptoolkit-website/assets/22168189/f50917f5-1b81-477b-96e7-1e4be8592882">

<img width="899" alt="Screenshot 2024-03-06 at 10 19 23" src="https://github.com/bejamas/httptoolkit-website/assets/22168189/bb63595d-ebca-4de5-bd49-d9ee575b76f3">

2024-03-06 19:56 UTC, merged